num1 = int(input('Enter your first number: '))
num2 = int(input('Enter your second number: '))
print('The addition of the two numbers is: ',num1+num2)
print('The subbtraction of the two numbers is: ',num1-num2)
print('The multiplication of the two numbers is: ',num1*num2)
print('The division of the two numbers is: ',num1/num2)
print('The floor division of the two numbers is: ',num1//num2)
print('The modulus of the two numbers is: ',num1%num2)
print('The square of num1 is: ',num1**2)
print('The cube of num2 is: ',num2**3)